### ISSUE TITLE
Get project configuration from a ".samson.yml"

### ISSUE THREAD

**Issue by xakraz** [zendesk/samson#191]
It could be great to be able to _define the stages_ and associated commands to run from a YML files like travis and co...

``` yml
deploy:

  stages:
    demo:
      command:
      permalink:
      confirm:
      e-mail:
...
```

Sansom will 
- clone the project
- Get and parse the `.samson.yml`
- Identify and create the different stages / commands
