### ISSUE TITLE
Error on all new k8s projects on deploy: JobExecution failed: metadata.labels.project must be consistent

### ISSUE THREAD

**Issue by rata** [zendesk/samson#2132]
Hi!

We are trying to create a new project and deploy with samson, but it fails with:

```
JobExecution failed: metadata.labels.project must be consistent
```

We are using `v1556` currently and probably never created a new project in samson since we upgraded to that version. So that might be related. We can deploy on all existing projects, though, except this one that we just created (added the rol, etc. as always)

The yaml we are using is at the end, just in case.

I've been struggling with this for a while now. Is there anything I'm missing? What needs to be done to satisfy the validation that I'm not seeing?

I see this validation has been added in commit e7d90b4a1dee506ac359c8f49f9ce0a6bf789f7a and I see there are a few patches later in master to disable it in some cases.

Do you see something obviously wrong (at the samson verification layer, at the k8s layer I think this works just fine) that I don't understand in this samson version? Or should I write a patch?

I really think it's something silly I'm missing, as probably you would had notified before (except for multi-projects and that stuff that was added later to disable this check, but probably not all projects are like that on your setup either, right?).

Thanks a lot and sorry for the trouble :)

```
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: adboy-web
  labels:
    project: adboy
    role: web
spec:
  replicas: 1
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 0
  selector:
    matchLabels:
      project: adboy
      role: web
  template:
    metadata:
      labels:
        project: adboy
        role: web
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: adboy
        image: <account-nr>.dkr.ecr.us-east-1.amazonaws.com/adboy:latest
        env:
        - name: RACK_ENV
          valueFrom:
            configMapKeyRef:
              name: global-apps
              key: pod-env
        volumeMounts:
        - mountPath: /nginx-pd
          name: nginx-volume
          readOnly: false
      - name: nginx
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/nginx:v0.10
        readinessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /health
            port: 80
        livenessProbe:
          initialDelaySeconds: 5
          httpGet:
            path: /health
            port: 80
        lifecycle:
         preStop:
          exec:
           command: ["nginx", "-s", "quit"]
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /nginx-pd
          name: nginx-volume
          readOnly: true
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
      - name: heka
        image: <account-id>.dkr.ecr.us-east-1.amazonaws.com/heka:v1.9
        env:
        - name: POD_ENV
          valueFrom:
            configMapKeyRef:
              name: global-apps
              key: pod-env
        - name: APP_NAME
          value: "adboy"
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
      volumes:
      - name: nginx-volume
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: adboy-web
  labels:
    project: adboy
    role: web
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
    protocol: TCP
  selector:
    project: adboy
    role: web
```
