### ISSUE TITLE
Evaluating environment variables in k8s manifests

### ISSUE THREAD

**Issue by nayena** [zendesk/samson#3127]
After having set up samson to deploy containers to kubernetes, using externally build images and enabling the appropriate configuration flags, I am very happy about how things work so far.

We've run into a slight issue with environment variables not being evaluated and substituted in the manifests, which we'd like to have, for our load balancer to have desired endpoints defined on a per environment basis, so it can fetch certs from lets encrypt.

The manifest looks like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kube
  labels:
    app: hello-kube
    project: hello-kube
    role: hello-kube
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: $DOMAIN_POSTFIX
    http:
      paths:
      - backend:
          serviceName: hello-kube
          servicePort: 80
```

this is only a part, see the full yaml in [this gist](https://gist.github.com/nayena/bdd7eb6b58e46b05ab4676ecb2419e72)

For testing purposes, the `$DOMAIN_POSTFIX` variable is alone, but i'd like to use it as a postfix later, so it would be something along: `host: hello.$DOMAIN_POSTFIX`.

When deploying our role, this is the error line, indicating that the variable isn't evaluted:
```
[10:18:24] Deploying Stage role hello-kube
[10:18:24] JobExecution failed: Kubernetes error hello-kube default Stage: Ingress.extensions "hello-kube" is invalid: spec.rules[0].host: Invalid value: "$DOMAIN_POSTFIX": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
As you can see, the environment tab shows the variable as present, and it is configured in a deploy-group.
![environment](https://user-images.githubusercontent.com/584251/51312949-be0efa00-1a4c-11e9-8ce7-af874bd09f54.png)

Looking at the group previewer (at /environment_variable_groups/preview?project_id=3), I see the variable as well:

![preview](https://user-images.githubusercontent.com/584251/51313199-4b524e80-1a4d-11e9-94a6-87893f9f6906.png)

and it is also selected in the settings for the project:
![project settings](https://user-images.githubusercontent.com/584251/51313310-7fc60a80-1a4d-11e9-965f-ff72a795b69b.png)

Are we doing it wrong or is this not an option in samson?
