### ISSUE TITLE
Utilizing set_via_env_json substition on Ingress causes a NoMethodError for nil:NilClass

### ISSUE THREAD

**Issue by nayena** [zendesk/samson#3136]
With the following manifest, a `NoMethodError on nil:NilClass` is thrown:

```
ErrorNotifier: NoMethodError - undefined method `dig_fetch' for nil:NilClass - /app/plugins/kubernetes/app/models/kubernetes/template_filler.rb:450:in `block in static_env'
/app/plugins/kubernetes/app/models/kubernetes/template_filler.rb:449:in `each'
/app/plugins/kubernetes/app/models/kubernetes/template_filler.rb:449:in `static_env'
/app/plugins/kubernetes/app/models/kubernetes/template_filler.rb:88:in `block in set_via_env_json'
/app/plugins/kubernetes/app/models/kubernetes/template_filler.rb:81:in `each'
/app/plugins/kubernetes/app/models/kubernetes/template_filler.rb:81:in `set_via_env_json'
```

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-kube
  labels:
    app: hello-kube
    project: hello-kube
    role: hello-kube
  annotations:
    kubernetes.io/ingress.class: traefik
    samson/set_via_env_json-spec.rules.0.host: DOMAIN_POSTFIX
spec:
  rules:
  - host: foo
    http:
      paths:
      - backend:
          serviceName: hello-kube
          servicePort: 80
```

Looking at [/plugins/kubernetes/app/models/kubernetes/role_config_file.rb](https://github.com/zendesk/samson/blob/master/plugins/kubernetes/app/models/kubernetes/role_config_file.rb), it seems to rely on having `spec.templates`, but that usually isn't the case for ingress resources.
