### ISSUE TITLE
set_env_via_json with kube2iam causes kubernetes manifest to be invalid

### ISSUE THREAD

**Issue by nayena** [zendesk/samson#3167]
We'd like to use [Kube2iam](https://github.com/jtblin/kube2iam) for having pods assume roles - and different roles per stage, which makes it a great fit for `set_env_via_json`.

The syntax for using kube2iam with a deployment, is setting 

```
spec:
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: iam-arn
```
and using that with `set_env_via_json`, gives the follow manifest:

```
- apiVersion: apps/v1beta1
  kind: Deployment
  metadata:
    annotations:
      samson/set_via_env_json-spec.template.annotations.iam.amazonaws.com/role: IAM_ROLE
```
Looking at the release doc in samson, I can verify that the variable substitution has happened correctly, see [this gist](https://gist.github.com/nayena/bb88c319df86c3e79ec5c67a209b3eea) for full release doc.

Unfortunately, this throws the following error:

```
[15:34:55] JobExecution failed: Kubernetes error feed-management-operations datapipeline Data Pipeline Stage: Deployment.apps "feed-management-operations" is invalid: metadata.annotations: Invalid value: "samson/set_via_env_json-spec.template.annotations.iam.amazonaws.com/role": a qualified name must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
```
